Repository hamzaahmedkhan/SpinnerDialog, pull requests merged in 2020-10, with the labels that each got.

#21 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#20 Create codacy-analysis.yml
  .github/workflows/codacy-analysis.yml
Labels: documentation, enhancement, hacktoberfest

#22 Migrate to AndroidX, Codacy workflow modified
  .github/workflows/codacy-analysis.yml
  app/build.gradle
  app/src/androidTest/java/com/github/hamzaahmedkhan/ExampleInstrumentedTest.kt
  app/src/main/java/com/github/hamzaahmedkhan/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  demo/SpinnerDialog.zip
  gradle.properties
  spinnerdialog/build.gradle
  spinnerdialog/src/androidTest/java/com/github/hamzaahmedkhan/spinnerdialog/ExampleInstrumentedTest.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/SpinnerDialogFragment.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/multi/SpinnerDialogMultiSelectAdapter.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/single/SpinnerDialogSingleSelectAdapter.kt
  spinnerdialog/src/main/res/layout/fragment_spinner_popup.xml
Labels: enhancement, hacktoberfest

#28 Release/1.2.3
  .github/workflows/greetings.yml
  README.md
  app/build.gradle
  app/src/main/java/com/github/hamzaahmedkhan/Constants.kt
  app/src/main/java/com/github/hamzaahmedkhan/MainActivity.kt
  demo/list_0.png
  demo/list_4.png
  demo/list_5.png
  spinnerdialog/build.gradle
  spinnerdialog/src/main/AndroidManifest.xml
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/enums/ImageType.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/extension/ViewExtension.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/models/SpinnerModel.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/SpinnerDialogFragment.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/multi/SpinnerDialogMultiSelectAdapter.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/single/SpinnerDialogSingleSelectAdapter.kt
  spinnerdialog/src/main/res/drawable-anydpi/img_bird.jpg
  spinnerdialog/src/main/res/drawable-anydpi/img_error.png
  spinnerdialog/src/main/res/drawable-anydpi/img_placeholder.png
  spinnerdialog/src/main/res/layout/item_spinner_dialog.xml
  spinnerdialog/src/main/res/layout/item_spinner_dialog_with_checkbox.xml
Labels: hacktoberfest, release

#29 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#30 Disable multiline on search input bar
  spinnerdialog/src/main/res/layout/fragment_spinner_popup.xml
Labels: bug

#31 Add divider below the search bar
  spinnerdialog/src/main/res/layout/fragment_spinner_popup.xml
  spinnerdialog/src/main/res/layout/item_spinner_dialog.xml
  spinnerdialog/src/main/res/layout/item_spinner_dialog_with_checkbox.xml
Labels: enhancement

#32 Restrict orientation to portrait mode only
  app/src/main/AndroidManifest.xml
Labels: enhancement

#33 Add properties to specify image dimensions on initialization
  app/src/main/java/com/github/hamzaahmedkhan/MainActivity.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/extension/ViewExtension.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/SpinnerDialogFragment.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/multi/SpinnerDialogMultiSelectAdapter.kt
  spinnerdialog/src/main/java/com/github/hamzaahmedkhan/spinnerdialog/ui/single/SpinnerDialogSingleSelectAdapter.kt
Labels: enhancement, hacktoberfest
